### ISSUE TITLE
[☂️ DRAFT] Umbrella Ticket for automated E2E Relay

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#126]
## Objective

[ What? Describe the issue in 1-2 sentences]

## Origin Document

[ Why? Justify the issue in 1-2 sentences. Consider adding a link or a screenshot.]

## Goals

- ...

## Deliverables

- ...

## Non-goals / Non-deliverables

- ...

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: [GitHub handle of issue owner]
**Co-Owners**: [OPTIONAL - GitHub handle of co-owner(s)]
