### ISSUE TITLE
[☂️ Documentation] Umbrella ticket to update all-the-docs

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#159]
## Objective

Improve the poktroll docs to enable external contributors and 3rd party gateways.

## Origin Document

The documentation in [pokt-network/poktroll](https://github.com/pokt-network/poktroll) fell behind as development kicked off. The bar in [pokt-network/pocket](pokt-network/pocket), and we want to get at least halfway there.

## Goals

- Create a better onboarding experience for anyone who comes by the [pokt-network/poktroll](https://github.com/pokt-network/poktroll) repo.
- Achieve "close to parity" with the prior "v1" repo
- Enable 3rd party gateways to easily understand & integrate with Shannon TestNet
- Share the development, work & research we have done with other projects in the ecosystem

## Deliverables

- [ ] [Everyone] Add missing architectural diagrams for this repo, where appropriate (new, migrated, etc...)
- [ ] [Everyone] Move over diagrams from [alpha repo](https://github.com/pokt-network/poktroll-alpha)
- [ ] [@bryanchriswhite] Move over our best practices (code reviews, coding guidelines, etc..) from the [v1](https://github.com/pokt-network/pocket)
- [ ] [@okdas] Make sure documentation related to DevNet, Telemetry & Observability is easily accessible
- [ ] [@h5law] Add documentation related to the usage & integration of the SMT
- [ ] [@red-0ne ] Provide documentation on the design and use of `AppGate`
- [ ] [@RossiNYC] Identify which tool (e.g. [GitBook](https://www.gitbook.com/), [Docusaurus](https://docusaurus.io/)) we want to use to mirror our documentation in this repo.
- [ ] [@Olshansk] Update the main entrypoint README

---

**Creator**: @Olshansk 
**Co-Owners**: @red-0ne @bryanchriswhite @okdas @h5law @RossiNYC

**Comment by Olshansk** [comment]
Sharing notes from a team meeting today o how we'll distribute some of the work on documentation:
- [ ] @bryanchriswhite @Olshansk: choose a platform for docs to make them more discoverable (gitbook, docusaurus, etc...) and decide how it should be organized
- [ ] @Olshansk: Update the main README, developer resources, onboarding, education, etc...
- [ ] @Olshansk: High-level architecture (i.e. component diagram) showing the interaction between pocket actors, the DA layer, sequencers, etc...
- [ ] @Olshansk: E2E Claim & Proof lifecycle (docs & sequence diagram)
- [ ] @bryanchriswhite: RelaySessionManager  + a few other `/pkg` (docs & component diagrams)
- [ ] @bryanchriswhite + @red-0ne: E2E Relay Request & Response lifecycle (i.e. sequence diagrams)
- [ ] @okdas: LocalNet Infra
- [ ] @okdas: DevNet Infra
- [ ] @okdas: Block explorer
- [ ] @okdas: Observability, telemetry & Metrics
- [ ] @h5law: Everything related to 💍 
- [ ] @h5law: How Shannon handles generic payloads
- [ ] @h5law (review by @bryanchriswhite): Make sure depinject godocs are discoverable
- [ ] @h5law (review by @red-0ne): appgatesever docs & component diagram
- [ ] @red-0ne - Config files for the supplier, application & gateway
- [ ] @red-0ne - Gateway onboarding (SDKs, APIs, etc...)

**Comment by Olshansk** [comment]
@red-0ne Moving comment from #205 regarding config documentation.

Staking configs:
- App config -> for staking applications
- Gateway config -> for staking gateways
- Supplier config -> for staking suppliers

Operations configs:
- AppGate config -> for operating a gateway or an application
- RelayMiner config -> for operating a supplier

**Comment by Olshansk** [comment]
Been looking through some of the options and heavily leaning towards https://docusaurus.io/.

It'll require having a docs specific github repo, so we might need to migrate the docs from here to other to avoid some duplication, but seems to be the best standard so far.

**Comment by RossiNYC** [comment]
@Olshansk - PNF already moving legacy POKT docs to Gitbook - wouldn't we just piggy back that? https://docs.pokt.network/

**Comment by Olshansk** [comment]
Closing this out as we already have a large portion of the docs in place.
