### ISSUE TITLE
[META] Figure out how to call our binaries & images

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#166]
## Objective

Let's decide on how we want our binary called. `pocketd`, `poktrolld` or something else? It might be a good opportunity to discuss this as we separate the different actors into their binaries. E.g. `pocketd` could be a sequencer, we could have a `relayer`, etc.

## Origin Document

After we renamed `pocketd` into `poktrolld`, we've ended up having some confusion around naming. 

## Goals

- Discuss w/ the team on how we should name our binaries
- Create and assign issues if there's any substantial amount of work required;

## Deliverables

- [ ] Choose `pocketd`, `poktrolld` or other for the sequencer binary
- [ ] Identify how many binaries we'll need for prod (e.g `Supplier`, `Gateway`, etc...)
- [ ] Rename and create the necessary binaries

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @okdas 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@okdas Updated some of the goals & deliverables. PTAL

**Comment by Olshansk** [comment]
Duplicate of #495
