### ISSUE TITLE
[Specifications] Morse -> Shannon Parity Checklist

### ISSUE THREAD

**Issue by RossiNYC** [pokt-network/poktroll#201]
## Objective

Define what "parity" means for the Shannon testnet 
If possible, overlay and/or x-ref the BlockSci scenarios 

## Origin Document

Look here: https://docs.google.com/spreadsheets/d/1B702g7982HOgUQTJB4t73J0yo6JcZ_nx9adNd14rLDM/edit#gid=0

## Goals

1. Everyone is working off the same definition / feature list
2. We don't forget anything 

## Deliverables

1. We keep the linked sheet up-to-date

## Non-goals / Non-deliverables

Replicating the content of the sheet in a GH issue

**Creator**: @RossiNYC

**Comment by Olshansk** [comment]
@RossiNYC I see the deliverables & goals you put out for this ticket and wanted to challenge what we aim to get out of this task. I realize this may be pedantic, and you explicitly implied what I'm sharing below, but I wanted to clearly align on goals, objectives & deliverables.

---

# Before

<img width="821" alt="Screenshot 2023-12-19 at 3 46 03 PM" src="https://github.com/pokt-network/poktroll/assets/1892194/947fba10-2180-4835-8445-43a727ba4e6e">

---

# After

## Objective

From a feature standpoint, define what `parity` means for the Shannon TestNet.

## Origin Document

[WIP Spreadsheet to track feature](https://docs.google.com/spreadsheets/d/1B702g7982HOgUQTJB4t73J0yo6JcZ_nx9adNd14rLDM/edit#gid=0).

## Goals

1. Align on must-have, nice-to-have and out-of-scope features for Shannon TestNet & MainNet
2. Increase the community's visibility into what exactly Shannon is shipping and is not
3. Identify discrepancies between Morse & Shannon

## Deliverables

- [ ] TestNet - Prepare a document that explicitly states the following:
	- [ ] Must-have features
	- [ ] Nice-to-have features
	- [ ] Out-of-scope features
- [ ] MainNet - Prepare a document that explicitly states the following:
	- [ ] Must-have features
	- [ ] Nice-to-have features
	- [ ] Out-of-scope features
- Post Mainnet
	- [ ] Prepare a rough document of post-mainnet wishlist features
- Discrepancy
	- [ ] 	Use the above to prepare a document that identifies the diff (+ / -) between Morse & Shannon
- Visibility
	- [ ] Make the document accessible in our docs so anyone in the community can visit it
	- [ ] Present the document above at a builder's call

## Non-goals / Non-deliverables

- Mapping the results of this exercise to BlockSci scenarios

**Comment by Olshansk** [comment]
Living doc is here: https://www.notion.so/buildwithgrove/Active-WIP-Morse-Shannon-Feature-Migration-938a28627ba0478d90d14a8d1d522757?pvs=4

**Comment by moatus** [comment]
Areas that need clarification: https://www.notion.so/buildwithgrove/Unanswered-Parity-Questions-7aa20d1ff39346b9b867f4a5f21f17b2

**Comment by Olshansk** [comment]
> Areas that need clarification: [notion.so/buildwithgrove/Unanswered-Parity-Questions-7aa20d1ff39346b9b867f4a5f21f17b2](https://www.notion.so/buildwithgrove/Unanswered-Parity-Questions-7aa20d1ff39346b9b867f4a5f21f17b2)

@moatus Great questions and ty for putting together the list. I've replied in line with detail/nuance where applicable.

**Comment by moatus** [comment]
Draft 1 of Shannon Overview was completed. Team feedback was provided and will be finalizing a Draft 2.

Tokenomics almost completed for review as well.

**Comment by moatus** [comment]
Shannon Overview is completed. PNF to publish this week.

**Comment by moatus** [comment]
https://docs.pokt.network/pokt-protocol/shannon/technical-overview/morse-greater-than-shannon-migration/pip-migration
