### ISSUE TITLE
[Stories] E2E User Stories for MainNet functionality

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#26]
## Objective

Design a set of user stories that'll capture E2E functionality and will be translated into E2E user tests. 
Use BlockSci research as input

## Origin Document

Ref Materials:
- [Shannon Features](https://docs.google.com/spreadsheets/d/1B702g7982HOgUQTJB4t73J0yo6JcZ_nx9adNd14rLDM/edit#gid=0)
- [E2E Feature List](https://github.com/pokt-network/pocket/blob/main/utility/doc/E2E_FEATURE_LIST.md)
- [BlockSci Action Chain Tracking Sheet](https://docs.google.com/spreadsheets/d/11O-BMlL4XEyx4uLPf3nCKfy_c9tWaT2C0EajifZxumE/edit#gid=0)

## Goals

- Identify 10-20 user stories that will capture MVP MainNet functionality
- Create a base of E2E stories that will be translated into automated tests
- Set the standard for creating user stories for features in the future

## Deliverables

- [ ] Tasks List below will include: User Story, BDD-Gherkin Syntax and link to Control Flow, Policy, and State (as part of the BlockSci documentation) - default parameters, etc. to be added as available. 

- [x] Choose an approach of how we should define/present user stories. For example:
	- [Mermaid Sequencer Diagrams](https://mermaid.js.org/syntax/sequenceDiagram.html); visual
	- [Cucamber Gherkin Syntax](https://cucumber.io/docs/gherkin/reference/); directly translates to tests
	- User Stories - (e.g. As an Application, I need X, Because Y)
- [ ] Make sure that each on-chain actor/participant (Account, Application, Gateway, Supplier, Sequencer) is involved in at least 3 end-to-end follows that touch the end user such as:
	- An E2E relay
	- Staking & unstaking
	- Transferring funds
	- Etc...

## Non-goals / Non-deliverables

- Designing E2E User Stories for non-MVP functionality
- Accounting for every possible edge case

---

**Creator**: @Olshansk 
**Co-Owners**: @RossiNYC
```[tasklist]
### Tasks
- [ ] https://github.com/pokt-network/poktroll/issues/97
- [ ] https://github.com/pokt-network/poktroll/issues/98
- [ ] https://github.com/pokt-network/poktroll/issues/102
- [ ] https://github.com/pokt-network/poktroll/issues/113
- [ ] https://github.com/pokt-network/poktroll/issues/154
- [ ] https://github.com/pokt-network/poktroll/issues/155
- [ ] [Supplier] Forced Unstaking to remove from Network
- [ ] [Supplier] Pause to Hibernate but remain in the Network
```

**Comment by RossiNYC** [comment]
Cucumber/BDD is a collection of practices that build upon agile ways of working (requires agile user stories as an input), helping teams succeed. For these practices to deliver value, you'll need to be working in an agile way. - Cucumber School

I am unfamiliar with BDD so I signed up for the free online course for PMs - its a process that builds off tradition agile concepts like user stories, etc. - I will complete the class in the next day or two and then give more feedback on this but I wanted to call this out now - BDD is not a replacement option for Agile or User Stories, its more like an addition step in the Agile process that helps align Documentation-Testing-Code in a stronger way (which is cool and seems like a great idea if we  agree we want/need this kind of process step)

**Comment by RossiNYC** [comment]
All good, think we need those to start as they inform the other presentation options. BDD is not a replacement, it's a way to express user stories in a way that can be automated, and then of course I like mermaid for the visuals.

**Comment by Olshansk** [comment]
@RossiNYC Please see the comment I left [here](https://github.com/pokt-network/poktroll/issues/98#issuecomment-1786248675). I realize formatting is just a small NIT but adds a lot in how these stories are read by others.

For example, see the difference between the edited & unedited one:

![Screenshot 2023-11-01 at 10 51 43 AM](https://github.com/pokt-network/poktroll/assets/1892194/0ae47f4b-3f70-4453-bb87-fe511b8fcd78)

![Screenshot 2023-11-01 at 10 51 35 AM](https://github.com/pokt-network/poktroll/assets/1892194/be940d61-4007-4dd5-b0f5-fba0b30d3660)
