### ISSUE TITLE
[Config] Add stake amount to the staking commands configs

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#293]
## Objective

Currently, the stake amount is excluded from the configuration files used to source staking command parameters of gateway, application and supplier actors.

Include the staking amount into these config files and make the parsers handle them, instead of providing them separately as a command argument.

## Origin Document

![image](https://github.com/pokt-network/poktroll/assets/231488/3541e27c-1a8e-488c-9624-a85eee601fc4)
https://discord.com/channels/824324475256438814/1138895490331705354/1187890061149229136

## Goals

- Make application config parser handle the amount to stake.
- Make supplier config parser handle the amount to stake.
- Create a config parser for the gateway staking command.

## Deliverables

- [x] PR to have staked amount handled by the stake application config parser #299 
- [x] PR to have staked amount handled by the stake supplier config parser #300 
- [x] PR to have gateway staking config parser #302

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @red-0ne
