### ISSUE TITLE
[Proof] Claim & proof distribution validation

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#402]
## Objective

The proof module SHOULD validate that claim and proof messages are submitted after a minimum delay, in blocks, after the respective session has ended to mitigate congestion caused by many (potentially all) suppliers submitting claims/proofs at the same time.

## Origin Document

![image](https://github.com/pokt-network/poktroll/assets/600733/11abb71f-e017-4e0c-ac4b-b83fdf908815)

![image](https://github.com/pokt-network/poktroll/assets/600733/03169008-3723-459a-8b11-1fad7008bab9)

## Goals

- Define gov. params in the proof module sufficient to support a "global" delay/offset in claim/proof the message distribution validation implementation.

See the application and service modules for examples of modules with params:
- Application: `max_delegated_gateways`
  - `proto/poktroll/application/params.proto`
  - `x/application/types/genesis_test.go`
  - `x/application/types/params.go`
  - `x/application/keeper/msg_server_delegate_to_gateway.go` (NB: `k.GetParams()`)
  - `x/application/keeper/msg_update_params_test.go` (application module may not be a good example; however, it seems like there should be tests that exercise updates for all params)

## Deliverables

- [ ] ~~A PR which adds `claim_msg_distribution_block_offset` to the proof module.~~ (duplicates #516 )
- [ ] ~~A PR which adds `proof_msg_distribution_block_offset` to the proof module.~~ (duplicates #516)
- [ ] ~~A PR which implements claim/proof message distribution validation using only these gov. params (omitting pseudo-random factor) & corresponding off-chain pkg changes.~~ (duplicates #516)
- [x] A PR which adds the pseudo-random factor to claim/proof message distribution validation (last block hash?).
  - Keeper has no API to query for past blocks (& hashes) by default (i.e. depends "block hash store").
  - Simplify "block hash store" to only store relevant blocks?

## Non-goals / Non-deliverables

- Introducing new gov. params other than those outlined in this issue.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @red-0ne, @Olshansk

**Comment by bryanchriswhite** [comment]
TODO: Rewrite this ticket to focus only on the randomized offset components. Global offset params are covered in #516.

**Comment by Olshansk** [comment]
@bryanchriswhite We have the `potential community` label which can be used as a backlog for future `community` tickets, but also acts as a `tentative` as well in case we decide it's not community compatible.
