### ISSUE TITLE
[Living Ticket] Prepare tickets/work that need to be completed during Alpha TestNet

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#437]
## Objective

Define & document success criteria as a Minimum Viable TestNet.

## Origin Document

This is the Minimum Viable TestNet iteration!

## Goals

- Communicate what's included in the Pocket Network Private Shannon TestNet (to the team & community)
- Clearly defining what features are in & out of scope
- Documenting how to easily access, view and use the private TestNet
- Scoping out work & requirements that need to be done between Private & Public TestNet

### Alpha TestNet
- [x]  Unbonding (after unstaking) periods for all actors #489
- [x]  (Un)jailing #490
- [x] Custodial & non-custodial staking #493
- [x]  RTTM - The equivalent of this in Shannon #494
- [x]  RevShare - The equivalent of this rom Morse #496
- [x]  App Transfer equivalent to Morse #657
- [x] `[Vital]` Min / Max / Required staking amounts for Application / Supplier / Gateway to reflect Shannon's tokenomics #612
- [x] `[Governance]` #625
	- [x] How do we handle consensus-breaking changes?
	- [x] How do we increase the block size like in Morse?
	- [x] How do we activate a new feature at a specific height?
	- [x] Document protocol updates and governance upgrades
- [x] `[Major]` Shannon tokenomics (source owners, etc...); https://docs.pokt.network/pokt-protocol/shannon #613
- [x] `[BLOCKET]` Comapre to `	curl --location -X 'POST' -H 'Content-Type: application/json' "${POCKET_ENDPOINT}/v1/query/allParams" | jq` and make sure we're not missing anything #660
- [x] `[Large]` Feature switch mechanism implementation & or documentation similar to Morse
- [x] Convert everything to using auto-cli
- [x] [Unbonding] Ticket to copy paste supplier unbonding for all other actors
- [x] [Staking] Ensure we have a ticket for this for each actor: Min / max stakes
- [x] Revisit tiered staking (15K, 30K, 45K, etc...) and whether we'll keep the same or a different system
- [x] [Proof] Ensure the threshold follows the Relay Mining logic
- [x] [TODO] TODO cleanup, beta and Everything under `x/`
- [x] Axelar TestNet Integration; https://docs.axelar.dev/resources/ibc-chain-onboarding#configure-your-keplr-wallet
- [x] [Document] All of the governance params we have
- [x] Ensure slashing conditions are clear in Shannon
- [x] Document how Tokenomics work with first release
- [x] Document the different between over/under/optimistically charging apps
- [x] Increase the fee for a new service -> add an event so PNF can subsidize it
	- [x] Update docs so its easy to add a new service
- [x] `[Scaling]` Start tracking Block size scalability in Shannon & what size of the block is used by proofs
- [x] `[NICE TO HAVE]` Simplify E2E Helpers using GPT
- [x] `[NICE TO HAVE]` GitHub action to catch lingering TODOs for closed issues / PRs
- [x] `[TBD POST_MAINNET]` Should there be a minimum number of nodes for a service?
- [x] `[TBD POST_MAINNET]`Use VoteExtensions to bring POKT/USD on-chain
- [x] `[TBD POST_MAINNET]` Tx/Gas Fees - Looking into Cosmos SDK gas fees and decide if Shannon should have a constant / variable tx fee and whether it should be related to POKT / USD price (incoming from POKT / USD)
- [x] `[TBD POST_MAINNET]` Align on a pattern (string, jwt, structure) for `service_ids`
- [x] `[TBD POST_MAINNET]` Add `domain_name` (or alternate name) for on-chain Gateways
---
**Creator**: @Olshansk

**Comment by Olshansk** [comment]
https://www.notion.so/buildwithgrove/Minimum-Viable-Testnet-Success-Criteria-baa2392d0c934f408a277c6afa1b226c?pvs=4

**Comment by Olshansk** [comment]
Created lots of detailed tickets for both the community & the team to cover in the coming weeks.

![Screenshot 2024-05-06 at 1 54 30 PM](https://github.com/pokt-network/poktroll/assets/1892194/0dc67873-b495-41f3-87f9-ec1fd39470cd)

**Comment by Olshansk** [comment]
This has undergone many iterations and a lot of effort was done.

Future work (leading up to and after beta testnet) can be found here: https://www.notion.so/buildwithgrove/Beta-TestNet-Preparation-7af6ee47925c4087b6ae11a13874fef2?pvs=4
