### ISSUE TITLE
[TODO] @Olshansk's (and now @Bryan's) Blocker TODOs

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#584]
## Objective

Tackle all on-chain blockers assigned to Olshansky

## Origin Document

- https://github.com/pokt-network/poktroll/pull/577
![Screenshot 2024-06-03 at 10 09 12 PM](https://github.com/pokt-network/poktroll/assets/1892194/3ccd2cbf-a09c-433a-9aa9-aff46004be05)

## Goals

- Tackle all major TODO's in the codebase assigned to Olshansky

## Deliverables

The output of the following command from https://github.com/pokt-network/poktroll/pull/577:

```bash
grep -r "TODO_BLOCKER(@Olshansk)" . | sed 's/^/- [ ] `/' | sed 's/:/`:/'
```

### #655

- #655 
- [x] `./pkg/relayer/miner/miner.go`:	// TODO_BLOCKER(@Olshansk): query on-chain governance params once available.

### #656

- #656
- [x] `./pkg/relayer/miner/miner.go`:// TODO_BLOCKER(@Olshansk): The relay hashing and relay difficulty mechanisms & values must come

### #629 

- #629
- [x] `./x/proof/keeper/msg_server_create_claim.go`:	// TODO_BLOCKER(@Olshansk): check if this claim already exists and return an
- [x] `./x/proof/keeper/msg_server_submit_proof.go`:	// TODO_BLOCKER(@Olshansk): check if this proof already exists and return an

### #659

- #659
- [x] `./x/proof/keeper/msg_server_submit_proof.go`:	// TODO_BLOCKER(@Olshansk): We need to replace the return

### #667

- #667
- [x] `./x/tokenomics/keeper/msg_update_params.go`:	// TODO_BLOCKER(@Olshansk): How do we validate this is the same address that signed the request?
- [x] `./pkg/relayer/proxy/relay_verifier.go`:	// TODO_BLOCKER(@Olshansk): Revisit the assumptions above and updated this if
- [x] `./x/session/keeper/session_hydrator.go`:	// TODO_BLOCKER(@Olshansk): Retrieve the suppliers at SessionStartBlockHeight,

### #668

- #668
- [x] `./x/proof/module/query_proof_test.go`:// TODO_BLOCKER(@Olshansk): Add these tests back in after merging on-chain Proof persistence.

### #669

- #669
- [x] `./x/tokenomics/keeper/settle_session_accounting.go`:		// TODO_BLOCKER(@Olshansk): The application should be immediately unstaked at this point in time

### #670

- #670 
- [x] `./x/tokenomics/keeper/settle_session_accounting_test.go`:	t.Skip("TODO_BLOCKER(@Olshansk): Add E2E and integration tests so we validate the actual state changes of the bank & account keepers.")
- [x] `./x/tokenomics/keeper/settle_session_accounting_test.go`:	t.Skip("TODO_BLOCKER(@Olshansk): Add E2E and integration tests so we validate the actual state changes of the bank & account keepers.")

### #656 

- #656 
- [x] `./pkg/relayer/protocol/difficulty.go`:// TODO_BLOCKER(@Olshansk): Remove the forloop logic and replace with a simplified

### #671

- #671
- [x] `./x/tokenomics/keeper/settle_pending_claims.go`:	// TODO_BLOCKER(@Olshansk): Optimize this by indexing expiringClaims appropriately

### https://github.com/pokt-network/smt/pull/50, https://github.com/pokt-network/smt/pull/51, & #672

- https://github.com/pokt-network/smt/pull/50
- https://github.com/pokt-network/smt/pull/51
- #672
- [x] `./x/tokenomics/keeper/settle_session_accounting.go`:	// TODO_BLOCKER(@Olshansk): This check should be the responsibility of the SMST package

---

**Creator**: @Olshansk

**Comment by Olshansk** [comment]
@bryanchriswhite Any chance you can tend to these in the next iteration? Doesn't seem like I'll have time...
