### ISSUE TITLE
[TODO] @bryanchriswhite's Iteration16 TODOs

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#586]
## Objective

Tackle all on-chain blockers assigned to @bryanchriswhite 

## Origin Document

- https://github.com/pokt-network/poktroll/pull/577
![Screenshot 2024-06-03 at 10 09 12 PM](https://github.com/pokt-network/poktroll/assets/1892194/3ccd2cbf-a09c-433a-9aa9-aff46004be05)

## Goals

- Tackle all major TODO's in the codebase assigned to @bryanchriswhite 

## Deliverables

The output of the following command from https://github.com/pokt-network/poktroll/pull/577:

```bash
grep -r "TODO_BLOCKER(@bryanchriswhite)" . | sed 's/^/- [ ] `/' | sed 's/:/`:/'
```

### #608

- #608
- [x] `./x/proof/types/query_validation.go`:	// TODO_BLOCKER(@bryanchriswhite): Validate the session ID once we have a deterministic way to generate it
- [x] `./x/proof/types/query_validation.go`:			Msg("TODO_BLOCKER(@bryanchriswhite): Validate the session ID once we have a deterministic way to generate it")
- [x] `./x/proof/types/query_validation.go`:	// TODO_BLOCKER(@bryanchriswhite): Validate the session ID once we have a deterministic way to generate it
- [x] `./x/proof/types/query_validation.go`:			Msg("TODO_BLOCKER(@bryanchriswhite): Validate the session ID once we have a deterministic way to generate it")

### #627 

- #627
- [x] `./x/proof/keeper/msg_server_create_claim.go`:	// TODO_BLOCKER(@bryanchriswhite): Prevent Claim upserts after the ClaimWindow is closed.
- [x] `./x/proof/keeper/msg_server_create_claim.go`:	// TODO_BLOCKER(@bryanchriswhite): Validate the signature on the Claim message corresponds to the supplier before Upserting.
- [x] `./x/proof/keeper/msg_server_submit_proof.go`:// TODO_BLOCKER(@bryanchriswhite): Prevent proof upserts after the tokenomics
- [x] `./pkg/relayer/session/session.go`:			// TODO_BLOCKER(@bryanchriswhite): Introduce governance claim and
- [x] `./load-testing/tests/relays_stress_helpers_test.go`:	// TODO_BLOCKER(@bryanchriswhite): replace with gov param query when available.
- [x] `./load-testing/tests/relays_stress_helpers_test.go`:	// TODO_BLOCKER(@bryanchriswhite): replace with gov param query when available.

### #628 

- #628
- [x] `./x/shared/types/params.go`:	// TODO_BLOCKER(@bryanchriswhite): Add `SessionGracePeriodBlocks` as a shared param,
- [x] `./x/shared/session.go`:// TODO_BLOCKER(@bryanchriswhite): This is a place-holder that will be removed

### #629 

- #629 
- [x] `./e2e/tests/session.feature`:    # TODO_BLOCKER(@bryanchriswhite): And a cosmos-sdk event (e.g. EventClaimCreated) should be emitted.
- [x] `./e2e/tests/session.feature`:    # TODO_BLOCKER(@bryanchriswhite): And a cosmos-sdk event (e.g. EventClaimCreated) should be emitted.

### #478

- #478
- [x] `./x/proof/keeper/msg_server_submit_proof.go`:		TODO_BLOCKER(@bryanchriswhite): Document these steps in proof

---

**Creator**: @bryanchriswhite

**Comment by bryanchriswhite** [comment]
Closing despite #629 still being in review as it is tracked by #580
