### ISSUE TITLE
[TODO] @okdas iteration16 TODOs

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#587]
## Objective

Need to address the blocking TODOs assigned to @okdas

## Origin Document

#577

## Goals

- Address blocker todos
- Investigate the next portion, less critical todos and create an issue for them

## Deliverables

```
grep -r "TODO_BLOCKER(@okdas" . | sed 's/^/- [ ] `/' | sed 's/:/`:/'
```

- [x] `./Makefile`:# TODO_BLOCKER(@okdas): bump `golangci-lint` when we upgrade golang to 1.21+
- [x] `./Tiltfile`:# TODO_BLOCKER(@okdas): Import validator keys when we switch to `poktrolld` helm chart
- [ ] `./x/shared/helpers/service_configs.go`:			// TODO_BLOCKER(@okdas): Validate configs once they are being used

---

**Creator**: @okdas
