### ISSUE TITLE
[Umbrella Ticket] Pocket Network TestNet Inteoperability

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#824]
## Objective

Identify the best solution to interoperability with Pocket network

## Origin Document

- [Hyperlane](https://hyperlane.xyz/)
- [Axelar](https://docs.axelar.dev/resources/ibc-chain-onboarding/)
- [Skip](https://medium.com/hyperlane/1-click-hyperlane-interoperability-with-skip-api-5ffd9bd0678c)
- [Chainlink CCIP](https://chain.link/cross-chain)
- Other callouts: EigenDA? Polymer? Layer0? Warmhole?

## Goals

- Increase POKT liquidity across different networks
- Make it easy for POKT to be listed on Tier 1 exchanges (e.g. coinbase)
- Focus on EVM integration / interoperability with a focus on the EVM
- Get an idea of what we should do in production
- Leverage the fact that the Cosmos SDK has IBC out of the box
- Eliminate as much custom development as possible

## Deliverables

- [ ] A proof-of-concept implement on top of TestNet
- [ ] Make sure to try out Axelar since they are IBC native, have a [self-serve solution](https://docs.axelar.dev/resources/ibc-chain-onboarding) and seem to be simpler than the others
- [ ] A notion doc capturing learnings along thew ay

## Non-goals / Non-deliverables

- Focus on security when it comes to interoperability
- General message passing

---

**Creator**: @Olshansk 
**Co-Owners**: @red-0ne

**Comment by Olshansk** [comment]
Quick update. 

The current direction this is taking from multiple conversations is:
1. Build an IBC channel with Osmosis
2. Use Axelar for EVM inteoeprability
3. Use skip.money to enable swaps & trades

We have ongoing conversations ith all teams.
